added new desktop tools
lucasgdb/useful-dev-tools pull request #294
Opened 2020-10-28 16:14 UTC by swetaayadav

2020-10-28 20:34 UTC, lucasgdb requested changes

2020-10-28 20:34 UTC, lucasgdb commented on desktop-tools.md
> +releated to building, testing and delivering or deploying software.
do not add an extra line.

2020-10-29 15:32 UTC, swetaayadav commented on desktop-tools.md
> +releated to building, testing and delivering or deploying software.
fixed

2020-10-29 15:41 UTC, lucasgdb approved these changes

2020-10-29 15:41 UTC, merged